/* Auto-generated by scripts/generate-content-manifest.mjs */
export const contentManifest = {
  "generatedAt": "2026-03-29T21:36:44.421Z",
  "contentRoot": "/content/desarrollo-frontend",
  "weeksCatalog": [
    {
      "id": "o1-in-web-development",
      "slug": "o1-in-web-development",
      "order": 1,
      "title": "Semana 1: In Web Development",
      "description": "Ruta de practica y proyectos para In Web Development.",
      "projects": [
        {
          "id": "o1-in-web-development-o1-pastor-chiribaya",
          "slug": "o1-pastor-chiribaya",
          "title": "Pastor Chiribaya",
          "sourcePath": "public/content/desarrollo-frontend/o1-in-web-development/o1-pastor-chiribaya/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o1-in-web-development/o1-pastor-chiribaya/index.html"
        },
        {
          "id": "o1-in-web-development-o2-elliotgaramendi",
          "slug": "o2-elliotgaramendi",
          "title": "Elliotgaramendi",
          "sourcePath": "public/content/desarrollo-frontend/o1-in-web-development/o2-elliotgaramendi/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o1-in-web-development/o2-elliotgaramendi/index.html"
        }
      ]
    },
    {
      "id": "o2-git-y-html",
      "slug": "o2-git-y-html",
      "order": 2,
      "title": "Semana 2: Git Y Html",
      "description": "Ruta de practica y proyectos para Git Y Html.",
      "projects": [
        {
          "id": "o2-git-y-html-o1-pastor-chiribaya",
          "slug": "o1-pastor-chiribaya",
          "title": "Pastor Chiribaya",
          "sourcePath": "public/content/desarrollo-frontend/o2-git-y-html/o1-pastor-chiribaya/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o2-git-y-html/o1-pastor-chiribaya/index.html"
        },
        {
          "id": "o2-git-y-html-o2-profile-card",
          "slug": "o2-profile-card",
          "title": "Profile Card",
          "sourcePath": "public/content/desarrollo-frontend/o2-git-y-html/o2-profile-card/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o2-git-y-html/o2-profile-card/index.html"
        },
        {
          "id": "o2-git-y-html-o4-mew",
          "slug": "o4-mew",
          "title": "Mew",
          "sourcePath": "public/content/desarrollo-frontend/o2-git-y-html/o4-mew/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o2-git-y-html/o4-mew/index.html"
        }
      ]
    },
    {
      "id": "o3-formularios-y-css",
      "slug": "o3-formularios-y-css",
      "order": 3,
      "title": "Semana 3: Formularios Y Css",
      "description": "Ruta de practica y proyectos para Formularios Y Css.",
      "projects": [
        {
          "id": "o3-formularios-y-css-o1-dev-portfolio",
          "slug": "o1-dev-portfolio",
          "title": "Dev Portfolio",
          "sourcePath": "public/content/desarrollo-frontend/o3-formularios-y-css/o1-dev-portfolio/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o3-formularios-y-css/o1-dev-portfolio/index.html"
        },
        {
          "id": "o3-formularios-y-css-o2-profile-card",
          "slug": "o2-profile-card",
          "title": "Profile Card",
          "sourcePath": "public/content/desarrollo-frontend/o3-formularios-y-css/o2-profile-card/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o3-formularios-y-css/o2-profile-card/index.html"
        },
        {
          "id": "o3-formularios-y-css-o3-anime-gallery",
          "slug": "o3-anime-gallery",
          "title": "Anime Gallery",
          "sourcePath": "public/content/desarrollo-frontend/o3-formularios-y-css/o3-anime-gallery /index.html",
          "sourceUrl": "/content/desarrollo-frontend/o3-formularios-y-css/o3-anime-gallery%20/index.html"
        }
      ]
    },
    {
      "id": "o4-fundamentos-de-css",
      "slug": "o4-fundamentos-de-css",
      "order": 4,
      "title": "Semana 4: Fundamentos De Css",
      "description": "Ruta de practica y proyectos para Fundamentos De Css.",
      "projects": [
        {
          "id": "o4-fundamentos-de-css-o1-dev-portfolio",
          "slug": "o1-dev-portfolio",
          "title": "Dev Portfolio",
          "sourcePath": "public/content/desarrollo-frontend/o4-fundamentos-de-css/o1-dev-portfolio/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o4-fundamentos-de-css/o1-dev-portfolio/index.html"
        },
        {
          "id": "o4-fundamentos-de-css-o2-profile-card",
          "slug": "o2-profile-card",
          "title": "Profile Card",
          "sourcePath": "public/content/desarrollo-frontend/o4-fundamentos-de-css/o2-profile-card/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o4-fundamentos-de-css/o2-profile-card/index.html"
        },
        {
          "id": "o4-fundamentos-de-css-o3-anime-gallery--animes",
          "slug": "o3-anime-gallery--animes",
          "title": "Anime Gallery / Animes",
          "sourcePath": "public/content/desarrollo-frontend/o4-fundamentos-de-css/o3-anime-gallery /animes/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o4-fundamentos-de-css/o3-anime-gallery%20/animes/index.html"
        },
        {
          "id": "o4-fundamentos-de-css-o3-anime-gallery",
          "slug": "o3-anime-gallery",
          "title": "Anime Gallery",
          "sourcePath": "public/content/desarrollo-frontend/o4-fundamentos-de-css/o3-anime-gallery /index.html",
          "sourceUrl": "/content/desarrollo-frontend/o4-fundamentos-de-css/o3-anime-gallery%20/index.html"
        }
      ]
    },
    {
      "id": "o5-layouts",
      "slug": "o5-layouts",
      "order": 5,
      "title": "Semana 5: Layouts",
      "description": "Ruta de practica y proyectos para Layouts.",
      "projects": [
        {
          "id": "o5-layouts-o1-dev-portfolio",
          "slug": "o1-dev-portfolio",
          "title": "Dev Portfolio",
          "sourcePath": "public/content/desarrollo-frontend/o5-layouts/o1-dev-portfolio/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o5-layouts/o1-dev-portfolio/index.html"
        },
        {
          "id": "o5-layouts-o2-mikhuy",
          "slug": "o2-mikhuy",
          "title": "Mikhuy",
          "sourcePath": "public/content/desarrollo-frontend/o5-layouts/o2-mikhuy/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o5-layouts/o2-mikhuy/index.html"
        },
        {
          "id": "o5-layouts-o3-anime-gallery",
          "slug": "o3-anime-gallery",
          "title": "Anime Gallery",
          "sourcePath": "public/content/desarrollo-frontend/o5-layouts/o3-anime-gallery/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o5-layouts/o3-anime-gallery/index.html"
        },
        {
          "id": "o5-layouts-o4-elliotgaramendi-cv",
          "slug": "o4-elliotgaramendi-cv",
          "title": "Elliotgaramendi Cv",
          "sourcePath": "public/content/desarrollo-frontend/o5-layouts/o4-elliotgaramendi-cv/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o5-layouts/o4-elliotgaramendi-cv/index.html"
        }
      ]
    },
    {
      "id": "o6-metodologias-y-preprocesadores",
      "slug": "o6-metodologias-y-preprocesadores",
      "order": 6,
      "title": "Semana 6: Metodologias Y Preprocesadores",
      "description": "Ruta de practica y proyectos para Metodologias Y Preprocesadores.",
      "projects": [
        {
          "id": "o6-metodologias-y-preprocesadores-o1-dev-portfolio",
          "slug": "o1-dev-portfolio",
          "title": "Dev Portfolio",
          "sourcePath": "public/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o1-dev-portfolio/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o1-dev-portfolio/index.html"
        },
        {
          "id": "o6-metodologias-y-preprocesadores-o2-starbucks",
          "slug": "o2-starbucks",
          "title": "Starbucks",
          "sourcePath": "public/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o2-starbucks/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o2-starbucks/index.html"
        },
        {
          "id": "o6-metodologias-y-preprocesadores-o3-dinodev-ai",
          "slug": "o3-dinodev-ai",
          "title": "Dinodev Ai",
          "sourcePath": "public/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o3-dinodev-ai/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o3-dinodev-ai/index.html"
        },
        {
          "id": "o6-metodologias-y-preprocesadores-o4-elliotgaramendi-cv",
          "slug": "o4-elliotgaramendi-cv",
          "title": "Elliotgaramendi Cv",
          "sourcePath": "public/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o4-elliotgaramendi-cv/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o4-elliotgaramendi-cv/index.html"
        },
        {
          "id": "o6-metodologias-y-preprocesadores-o5-gallery",
          "slug": "o5-gallery",
          "title": "Gallery",
          "sourcePath": "public/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o5-gallery/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o6-metodologias-y-preprocesadores/o5-gallery/index.html"
        }
      ]
    },
    {
      "id": "o7-diseño-responsivo-y-bootstrap",
      "slug": "o7-diseno-responsivo-y-bootstrap",
      "order": 7,
      "title": "Semana 7: Diseño Responsivo Y Bootstrap",
      "description": "Ruta de practica y proyectos para Diseño Responsivo Y Bootstrap.",
      "projects": [
        {
          "id": "o7-diseno-responsivo-y-bootstrap-o1-dev-portfolio",
          "slug": "o1-dev-portfolio",
          "title": "Dev Portfolio",
          "sourcePath": "public/content/desarrollo-frontend/o7-diseño-responsivo-y-bootstrap/o1-dev-portfolio/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o7-dise%C3%B1o-responsivo-y-bootstrap/o1-dev-portfolio/index.html"
        },
        {
          "id": "o7-diseno-responsivo-y-bootstrap-o2-sinespoiler",
          "slug": "o2-sinespoiler",
          "title": "Sinespoiler",
          "sourcePath": "public/content/desarrollo-frontend/o7-diseño-responsivo-y-bootstrap/o2-sinespoiler/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o7-dise%C3%B1o-responsivo-y-bootstrap/o2-sinespoiler/index.html"
        },
        {
          "id": "o7-diseno-responsivo-y-bootstrap-o3-animes",
          "slug": "o3-animes",
          "title": "Animes",
          "sourcePath": "public/content/desarrollo-frontend/o7-diseño-responsivo-y-bootstrap/o3-animes/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o7-dise%C3%B1o-responsivo-y-bootstrap/o3-animes/index.html"
        }
      ]
    },
    {
      "id": "o8-introduccion-a-javascript",
      "slug": "o8-introduccion-a-javascript",
      "order": 8,
      "title": "Semana 8: Introduccion A Javascript",
      "description": "Ruta de practica y proyectos para Introduccion A Javascript.",
      "projects": [
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o1-first-message",
          "slug": "level-01--challenges--o1-first-message",
          "title": "Level / Challenges / First Message",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o1-first-message/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o1-first-message/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o10-capture-input",
          "slug": "level-01--challenges--o10-capture-input",
          "title": "Level / Challenges / Capture Input",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o10-capture-input/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o10-capture-input/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o11-custom-greeting",
          "slug": "level-01--challenges--o11-custom-greeting",
          "title": "Level / Challenges / Custom Greeting",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o11-custom-greeting/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o11-custom-greeting/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o12-mini-profile",
          "slug": "level-01--challenges--o12-mini-profile",
          "title": "Level / Challenges / Mini Profile",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o12-mini-profile/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o12-mini-profile/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o2-colored-messages",
          "slug": "level-01--challenges--o2-colored-messages",
          "title": "Level / Challenges / Colored Messages",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o2-colored-messages/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o2-colored-messages/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o3-first-variable",
          "slug": "level-01--challenges--o3-first-variable",
          "title": "Level / Challenges / First Variable",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o3-first-variable/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o3-first-variable/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o4-const-vs-let",
          "slug": "level-01--challenges--o4-const-vs-let",
          "title": "Level / Challenges / Const Vs Let",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o4-const-vs-let/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o4-const-vs-let/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o5-data-types",
          "slug": "level-01--challenges--o5-data-types",
          "title": "Level / Challenges / Data Types",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o5-data-types/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o5-data-types/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o6-type-detective",
          "slug": "level-01--challenges--o6-type-detective",
          "title": "Level / Challenges / Type Detective",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o6-type-detective /index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o6-type-detective%20/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o7-template-strings",
          "slug": "level-01--challenges--o7-template-strings",
          "title": "Level / Challenges / Template Strings",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o7-template-strings/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o7-template-strings/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o8-math-operations",
          "slug": "level-01--challenges--o8-math-operations",
          "title": "Level / Challenges / Math Operations",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o8-math-operations/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o8-math-operations/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-01--challenges--o9-first-alert",
          "slug": "level-01--challenges--o9-first-alert",
          "title": "Level / Challenges / First Alert",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o9-first-alert/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-01/challenges/o9-first-alert/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o1-magic-potions-lab",
          "slug": "level-02--challenges--o1-magic-potions-lab",
          "title": "Level / Challenges / Magic Potions Lab",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o1-magic-potions-lab/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o1-magic-potions-lab/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o2-truth-pig",
          "slug": "level-02--challenges--o2-truth-pig",
          "title": "Level / Challenges / Truth Pig",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o2-truth-pig/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o2-truth-pig/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o3-truthy-falsy",
          "slug": "level-02--challenges--o3-truthy-falsy",
          "title": "Level / Challenges / Truthy Falsy",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o3-truthy-falsy/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o3-truthy-falsy/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o4-magic-casino",
          "slug": "level-02--challenges--o4-magic-casino",
          "title": "Level / Challenges / Magic Casino",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o4-magic-casino/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o4-magic-casino/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o5-plus-curse",
          "slug": "level-02--challenges--o5-plus-curse",
          "title": "Level / Challenges / Plus Curse",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o5-plus-curse/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o5-plus-curse/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o6-equality-tribunal",
          "slug": "level-02--challenges--o6-equality-tribunal",
          "title": "Level / Challenges / Equality Tribunal",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o6-equality-tribunal/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o6-equality-tribunal/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o7-hogwarts-if-else",
          "slug": "level-02--challenges--o7-hogwarts-if-else",
          "title": "Level / Challenges / Hogwarts If Else",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o7-hogwarts-if-else/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o7-hogwarts-if-else/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o8-pet-personality-if-else",
          "slug": "level-02--challenges--o8-pet-personality-if-else",
          "title": "Level / Challenges / Pet Personality If Else",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o8-pet-personality-if-else/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o8-pet-personality-if-else/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-02--challenges--o9-mission-selector-switch",
          "slug": "level-02--challenges--o9-mission-selector-switch",
          "title": "Level / Challenges / Mission Selector Switch",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o9-mission-selector-switch/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-02/challenges/o9-mission-selector-switch/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o1-counter-for-loop",
          "slug": "level-03--challenges--o1-counter-for-loop",
          "title": "Level / Challenges / Counter For Loop",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o1-counter-for-loop/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o1-counter-for-loop/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o2-multiplication-for-nested",
          "slug": "level-03--challenges--o2-multiplication-for-nested",
          "title": "Level / Challenges / Multiplication For Nested",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o2-multiplication-for-nested/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o2-multiplication-for-nested/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o3-treasure-hunt-while",
          "slug": "level-03--challenges--o3-treasure-hunt-while",
          "title": "Level / Challenges / Treasure Hunt While",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o3-treasure-hunt-while/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o3-treasure-hunt-while/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o4-guess-break",
          "slug": "level-03--challenges--o4-guess-break",
          "title": "Level / Challenges / Guess Break",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o4-guess-break/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o4-guess-break/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o5-continue-even-numbers",
          "slug": "level-03--challenges--o5-continue-even-numbers",
          "title": "Level / Challenges / Continue Even Numbers",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o5-continue-even-numbers/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o5-continue-even-numbers/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o6-star-pyramid-nested",
          "slug": "level-03--challenges--o6-star-pyramid-nested",
          "title": "Level / Challenges / Star Pyramid Nested",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o6-star-pyramid-nested/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o6-star-pyramid-nested/index.html"
        },
        {
          "id": "o8-introduccion-a-javascript-level-03--challenges--o7-grid-search-nested-while",
          "slug": "level-03--challenges--o7-grid-search-nested-while",
          "title": "Level / Challenges / Grid Search Nested While",
          "sourcePath": "public/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o7-grid-search-nested-while/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o8-introduccion-a-javascript/level-03/challenges/o7-grid-search-nested-while/index.html"
        }
      ]
    },
    {
      "id": "o9-objetos-arrays-y-funciones",
      "slug": "o9-objetos-arrays-y-funciones",
      "order": 9,
      "title": "Semana 9: Objetos Arrays Y Funciones",
      "description": "Ruta de practica y proyectos para Objetos Arrays Y Funciones.",
      "projects": [
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o1-magic-backpack",
          "slug": "level-04--challenges--o1-magic-backpack",
          "title": "Level / Challenges / Magic Backpack",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o1-magic-backpack/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o1-magic-backpack/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o2-magic-train",
          "slug": "level-04--challenges--o2-magic-train",
          "title": "Level / Challenges / Magic Train",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o2-magic-train/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o2-magic-train/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o3-indexof-slice-detective",
          "slug": "level-04--challenges--o3-indexof-slice-detective",
          "title": "Level / Challenges / Indexof Slice Detective",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o3-indexof-slice-detective/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o3-indexof-slice-detective/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o4-foreach-map-factory",
          "slug": "level-04--challenges--o4-foreach-map-factory",
          "title": "Level / Challenges / Foreach Map Factory",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o4-foreach-map-factory/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o4-foreach-map-factory/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o5-filter-find-guardians",
          "slug": "level-04--challenges--o5-filter-find-guardians",
          "title": "Level / Challenges / Filter Find Guardians",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o5-filter-find-guardians/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o5-filter-find-guardians/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o6-spread-clan-fusion",
          "slug": "level-04--challenges--o6-spread-clan-fusion",
          "title": "Level / Challenges / Spread Clan Fusion",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o6-spread-clan-fusion/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o6-spread-clan-fusion/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-04--challenges--o7-destructuring-treasure",
          "slug": "level-04--challenges--o7-destructuring-treasure",
          "title": "Level / Challenges / Destructuring Treasure",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o7-destructuring-treasure/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-04/challenges/o7-destructuring-treasure/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-05--challenges--o1-hero-card-objects-basics",
          "slug": "level-05--challenges--o1-hero-card-objects-basics",
          "title": "Level / Challenges / Hero Card Objects Basics",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o1-hero-card-objects-basics/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o1-hero-card-objects-basics/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-05--challenges--o2-dynamic-chest-bracket-notation",
          "slug": "level-05--challenges--o2-dynamic-chest-bracket-notation",
          "title": "Level / Challenges / Dynamic Chest Bracket Notation",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o2-dynamic-chest-bracket-notation/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o2-dynamic-chest-bracket-notation/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-05--challenges--o3-nested-kingdom-objects",
          "slug": "level-05--challenges--o3-nested-kingdom-objects",
          "title": "Level / Challenges / Nested Kingdom Objects",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o3-nested-kingdom-objects/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o3-nested-kingdom-objects/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-05--challenges--o4-heroes-list-array-objects",
          "slug": "level-05--challenges--o4-heroes-list-array-objects",
          "title": "Level / Challenges / Heroes List Array Objects",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o4-heroes-list-array-objects/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o4-heroes-list-array-objects/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-05--challenges--o5-spread-destructure-recipes",
          "slug": "level-05--challenges--o5-spread-destructure-recipes",
          "title": "Level / Challenges / Spread Destructure Recipes",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o5-spread-destructure-recipes/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o5-spread-destructure-recipes/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-05--challenges--o6-json-save-hero",
          "slug": "level-05--challenges--o6-json-save-hero",
          "title": "Level / Challenges / Json Save Hero",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o6-json-save-hero/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-05/challenges/o6-json-save-hero/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-06--challenges--o1-magic-calculator-functions",
          "slug": "level-06--challenges--o1-magic-calculator-functions",
          "title": "Level / Challenges / Magic Calculator Functions",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o1-magic-calculator-functions/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o1-magic-calculator-functions/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-06--challenges--o2-power-transformer-arrows",
          "slug": "level-06--challenges--o2-power-transformer-arrows",
          "title": "Level / Challenges / Power Transformer Arrows",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o2-power-transformer-arrows/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o2-power-transformer-arrows/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-06--challenges--o3-default-params-lab",
          "slug": "level-06--challenges--o3-default-params-lab",
          "title": "Level / Challenges / Default Params Lab",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o3-default-params-lab/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o3-default-params-lab/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-06--challenges--o4-infinite-accumulator-rest",
          "slug": "level-06--challenges--o4-infinite-accumulator-rest",
          "title": "Level / Challenges / Infinite Accumulator Rest",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o4-infinite-accumulator-rest/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o4-infinite-accumulator-rest/index.html"
        },
        {
          "id": "o9-objetos-arrays-y-funciones-level-06--challenges--o5-array-processor-functions",
          "slug": "level-06--challenges--o5-array-processor-functions",
          "title": "Level / Challenges / Array Processor Functions",
          "sourcePath": "public/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o5-array-processor-functions/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o9-objetos-arrays-y-funciones/level-06/challenges/o5-array-processor-functions/index.html"
        }
      ]
    },
    {
      "id": "o10-dom-events-storage",
      "slug": "o10-dom-events-storage",
      "order": 10,
      "title": "Semana 10: Dom Events Storage",
      "description": "Ruta de practica y proyectos para Dom Events Storage.",
      "projects": [
        {
          "id": "o10-dom-events-storage-level-07--challenges--o1-magic-selector-queryselector",
          "slug": "level-07--challenges--o1-magic-selector-queryselector",
          "title": "Level / Challenges / Magic Selector Queryselector",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o1-magic-selector-queryselector/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o1-magic-selector-queryselector/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-07--challenges--o2-content-editor-innerhtml",
          "slug": "level-07--challenges--o2-content-editor-innerhtml",
          "title": "Level / Challenges / Content Editor Innerhtml",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o2-content-editor-innerhtml/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o2-content-editor-innerhtml/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-07--challenges--o3-style-changer-classlist",
          "slug": "level-07--challenges--o3-style-changer-classlist",
          "title": "Level / Challenges / Style Changer Classlist",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o3-style-changer-classlist/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o3-style-changer-classlist/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-07--challenges--o4-element-builder-createelement",
          "slug": "level-07--challenges--o4-element-builder-createelement",
          "title": "Level / Challenges / Element Builder Createelement",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o4-element-builder-createelement/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-07/challenges/o4-element-builder-createelement/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-08--challenges--o1-click-counter",
          "slug": "level-08--challenges--o1-click-counter",
          "title": "Level / Challenges / Click Counter",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-08/challenges/o1-click-counter/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-08/challenges/o1-click-counter/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-08--challenges--o2-magic-form-submit",
          "slug": "level-08--challenges--o2-magic-form-submit",
          "title": "Level / Challenges / Magic Form Submit",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-08/challenges/o2-magic-form-submit/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-08/challenges/o2-magic-form-submit/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-08--challenges--o3-live-search-input",
          "slug": "level-08--challenges--o3-live-search-input",
          "title": "Level / Challenges / Live Search Input",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-08/challenges/o3-live-search-input/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-08/challenges/o3-live-search-input/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-09--challenges--o1-immortal-notes",
          "slug": "level-09--challenges--o1-immortal-notes",
          "title": "Level / Challenges / Immortal Notes",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-09/challenges/o1-immortal-notes/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-09/challenges/o1-immortal-notes/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-09--challenges--o2-color-palette",
          "slug": "level-09--challenges--o2-color-palette",
          "title": "Level / Challenges / Color Palette",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-09/challenges/o2-color-palette/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-09/challenges/o2-color-palette/index.html"
        },
        {
          "id": "o10-dom-events-storage-level-09--challenges--o3-task-list-crud",
          "slug": "level-09--challenges--o3-task-list-crud",
          "title": "Level / Challenges / Task List Crud",
          "sourcePath": "public/content/desarrollo-frontend/o10-dom-events-storage/level-09/challenges/o3-task-list-crud/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o10-dom-events-storage/level-09/challenges/o3-task-list-crud/index.html"
        }
      ]
    },
    {
      "id": "o11-asincronia-apis-code",
      "slug": "o11-asincronia-apis-code",
      "order": 11,
      "title": "Semana 11: Asincronia Apis Code",
      "description": "Ruta de practica y proyectos para Asincronia Apis Code.",
      "projects": [
        {
          "id": "o11-asincronia-apis-code-level-10--o1-pomodoro-timer",
          "slug": "level-10--o1-pomodoro-timer",
          "title": "Level / Pomodoro Timer",
          "sourcePath": "public/content/desarrollo-frontend/o11-asincronia-apis-code/level-10/o1-pomodoro-timer/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o11-asincronia-apis-code/level-10/o1-pomodoro-timer/index.html"
        },
        {
          "id": "o11-asincronia-apis-code-level-10--o2-reaction-game",
          "slug": "level-10--o2-reaction-game",
          "title": "Level / Reaction Game",
          "sourcePath": "public/content/desarrollo-frontend/o11-asincronia-apis-code/level-10/o2-reaction-game/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o11-asincronia-apis-code/level-10/o2-reaction-game/index.html"
        },
        {
          "id": "o11-asincronia-apis-code-level-10--o3-api-simulator",
          "slug": "level-10--o3-api-simulator",
          "title": "Level / Api Simulator",
          "sourcePath": "public/content/desarrollo-frontend/o11-asincronia-apis-code/level-10/o3-api-simulator/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o11-asincronia-apis-code/level-10/o3-api-simulator/index.html"
        },
        {
          "id": "o11-asincronia-apis-code-level-11--o1-dog-gallery",
          "slug": "level-11--o1-dog-gallery",
          "title": "Level / Dog Gallery",
          "sourcePath": "public/content/desarrollo-frontend/o11-asincronia-apis-code/level-11/o1-dog-gallery/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o11-asincronia-apis-code/level-11/o1-dog-gallery/index.html"
        },
        {
          "id": "o11-asincronia-apis-code-level-11--o2-rick-morty-portal",
          "slug": "level-11--o2-rick-morty-portal",
          "title": "Level / Rick Morty Portal",
          "sourcePath": "public/content/desarrollo-frontend/o11-asincronia-apis-code/level-11/o2-rick-morty-portal/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o11-asincronia-apis-code/level-11/o2-rick-morty-portal/index.html"
        }
      ]
    },
    {
      "id": "o12-nodejs-y-npm",
      "slug": "o12-nodejs-y-npm",
      "order": 12,
      "title": "Semana 12: Nodejs Y Npm",
      "description": "Ruta de practica y proyectos para Nodejs Y Npm.",
      "projects": []
    },
    {
      "id": "o13-http-middleware",
      "slug": "o13-http-middleware",
      "order": 13,
      "title": "Semana 13: Http Middleware",
      "description": "Ruta de practica y proyectos para Http Middleware.",
      "projects": []
    },
    {
      "id": "o14-react",
      "slug": "o14-react",
      "order": 14,
      "title": "Semana 14: React",
      "description": "Ruta de practica y proyectos para React.",
      "projects": [
        {
          "id": "o14-react-o0-institutes",
          "slug": "o0-institutes",
          "title": "Institutes",
          "sourcePath": "public/content/desarrollo-frontend/o14-react/o0-institutes/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o14-react/o0-institutes/index.html"
        },
        {
          "id": "o14-react-o1-my-first-page",
          "slug": "o1-my-first-page",
          "title": "My First Page",
          "sourcePath": "public/content/desarrollo-frontend/o14-react/o1-my-first-page/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o14-react/o1-my-first-page/index.html"
        }
      ]
    },
    {
      "id": "o15-jsx-events",
      "slug": "o15-jsx-events",
      "order": 15,
      "title": "Semana 15: Jsx Events",
      "description": "Ruta de practica y proyectos para Jsx Events.",
      "projects": [
        {
          "id": "o15-jsx-events-o1-todo-list",
          "slug": "o1-todo-list",
          "title": "Todo List",
          "sourcePath": "public/content/desarrollo-frontend/o15-jsx-events/o1-todo-list/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o15-jsx-events/o1-todo-list/index.html"
        }
      ]
    },
    {
      "id": "o16-api-libraries",
      "slug": "o16-api-libraries",
      "order": 16,
      "title": "Semana 16: Api Libraries",
      "description": "Ruta de practica y proyectos para Api Libraries.",
      "projects": [
        {
          "id": "o16-api-libraries-o0-animes",
          "slug": "o0-animes",
          "title": "Animes",
          "sourcePath": "public/content/desarrollo-frontend/o16-api-libraries/o0-animes/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o16-api-libraries/o0-animes/index.html"
        }
      ]
    },
    {
      "id": "o17-global-deploy",
      "slug": "o17-global-deploy",
      "order": 17,
      "title": "Semana 17: Global Deploy",
      "description": "Ruta de practica y proyectos para Global Deploy.",
      "projects": [
        {
          "id": "o17-global-deploy-o0-rick-and-morty",
          "slug": "o0-rick-and-morty",
          "title": "Rick And Morty",
          "sourcePath": "public/content/desarrollo-frontend/o17-global-deploy/o0-rick-and-morty/index.html",
          "sourceUrl": "/content/desarrollo-frontend/o17-global-deploy/o0-rick-and-morty/index.html"
        }
      ]
    }
  ]
} as const
